### ISSUE TITLE
demo prep

### ISSUE THREAD

**Issue by Callisto13** [warehouse-13/cosmic#1]
This is a high level tracker issue to list all the pieces of work needed to make the talk pitch a reality.

> “Phenomenal Cosmic Powers! Itty Bitty Living Space!”, or How MicroVMs can take your Kubernetes home lab to the next level!

> Kubernetes on baremetal is not new, and there are a bunch of CAPI providers
which let you set up baremetal clusters alongside your standard virtualised ones.
But what if you wanted both, at the same time, in the same cluster, on the same devices? What if you wanted to change your mind on your setup, and do nothing more than a manifest update to switch the ratio of baremetal and virtualised nodes?
This is where MicroVMs and the Cluster API MicroVM Provider come in. In this talk Claudia and Josh will walk through what MicroVMs are, how they improve upon expensive and slow-to-boot virtualised nodes, how they can be used alongside baremetal resources, and how CAPMVM can bring those elements together to provision fast, scalable clusters, giving us the best of both worlds. Lastly they will do a live demo of a Raspberry Pi CAPMVM homelab, a super fun project for any engineer in the k8s space.

- [x] Research required components
- [x] Get a cost estimate for Liz to expense things
- [x] Buy all the bits
- [x] ARM images https://github.com/weaveworks-liquidmetal/image-builder/issues/29
  - [x] https://github.com/weaveworks-liquidmetal/image-builder/pull/43
  - [x] https://github.com/weaveworks-liquidmetal/image-builder/pull/44
  - [x] https://github.com/weaveworks-liquidmetal/image-builder/pull/45
- [x] Spike on how to actually do this
  - [x] https://github.com/weaveworks-liquidmetal/flintlock/pull/562
  - [x] https://github.com/weaveworks-liquidmetal/cluster-api-provider-microvm/pull/240
  - [x] release both flint and capmvm
  - [x] final networking hurdle: kube-vip ip  
- [ ] Write script https://github.com/warehouse-13/cosmic/issues/2
- [ ] Write slides https://github.com/warehouse-13/cosmic/issues/2
- [ ] Rehearsals (we can probs use the new internal team review format) 
- [ ] Liquid metal product documentation https://github.com/weaveworks-liquidmetal/flintlock/issues/207  https://github.com/weaveworks-liquidmetal/docs/issues/1
- [x] Update docs on this repo so that anyone can assemble a similar setup https://github.com/warehouse-13/cosmic/issues/4
- [x] Open source this repo and generate tiny url so we can get people involved: https://bit.ly/cosmic-homelab
- [ ] https://github.com/warehouse-13/cosmic/issues/5
